version: '3.8'

services:
  web:
    build: .
    container_name: backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/backend
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/dropcenter_wheel?currentSchema=postgres
      # - DATABASE_URL=postgresql://postgres:i4yUrooRXWQ7PT9GGNqk@dropcenter-db-prod.ctucgq2swzpj.us-east-1.rds.amazonaws.com/dropcenter_wheel
      # - DATABASE_URL=postgresql://postgres:3GjkLjmnIv3Ivw6IGoL5@dropcenter-db-stage.ctucgq2swzpj.us-east-1.rds.amazonaws.com/dropcenter_wheel
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=dropcenter_wheel

volumes:
  postgres_data:
